name: Release
run-name: ${{ github.actor }} is releasing wayfinder 🚀
on: 
  push:
    tags:
      - '*'

jobs:
  Create-Release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Decrypt developer key
        run: ./.github/scripts/decrypt_secret.sh
        env:
          INPUT: ./developer_key.gpg
          OUTPUT: ./developer_key
          PASSPHRASE: ${{ secrets.DEVELOPER_KEY_PASSPHRASE }}
      - name: Create release
        uses: blackshadev/garmin-connectiq-release-action@1.0.0
        with:
          projectJungle: ./monkey.jungle
          developerKey: ./developer_key
          outputPath: out/wayfinder.iq
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wayfinder-${{ github.ref_name }}
          path: out/wayfinder.iq

