name: Server CI/CD

permissions:
  contents: read
  packages: write

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/server

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install dependencies
        run: cd server && go get .
      - name: Go vet
        run: cd server && go vet ./...
      - name: Go tests
        run: cd server && go test ./...
      - name: Go build
        run: cd server && go build -v -o waypoint-server
  publish:
    needs: test
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/feature/waypoint-server'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: server
          file: server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update server image
        id: updateServer
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.PORTAINER_WEB_HOOK }}
          method: POST
      - name: Show Response
        run: |
          echo ${{ steps.updateServer.outputs.response }}
          echo ${{ steps.updateServer.outputs.headers }}
          echo ${{ steps.updateServer.outputs.status }}
          echo ${{ fromJson(steps.updateServer.outputs.response) }}